# Copyright 2020-2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

[workspace]
resolver = "2"
members = ["vtok_common", "vtok_p11", "pkcs11_aws_lc", "pkcs11_mock", "vtok_p11_trait"]
default-members = ["vtok_common", "vtok_p11", "pkcs11_aws_lc", "pkcs11_mock"]

[profile.release]
codegen-units=1
